name: CI

on:
  push:
    branches:
      - main
    pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_fmt:
    name: Clippy & Rustfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly
        os:
          - name: Ubuntu
            version: ubuntu-latest
          - name: Windows
            version: windows-latest
          - name: MacOS
            version: macos-latest

    name: Build & Test - ${{ matrix.os.name }} (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os.version }}

    steps:
      - uses: actions/checkout@v2
      - name: Install ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
